spring:
    thymeleaf:
        cache: false
    datasource:
        driver-class-name: org.h2.Driver  
        generate-unique-name: false
        name: marinesco
#        url: jdbc:h2:mem:marinesco
        url: jdbc:h2:file:/tmp/h22
        username: sa
        password:
    jpa:
        properties:
            hibernate:
                database-platform: org.hibernate.dialect.H2Dialect
#                format_sql: true
        hibernate: 
            ddl-auto: update
#        show-sql: true
    h2:
        console:
            enabled: true
            path: /h2
            settings:
                web-allow-others: true
                trace: false
logging:
    level:
        org:
            springframework: INFO
#    file:
#        path: "/tmp/log"
marinesco:
    library:
        filesLocation: "./lib"