version: '3.1'

services:
    marinesco:
        build: ./build
        image: loper:marinesco
        links:
            - postgres
        ports:
            - 80:8080
        volumes:
            - ./files/root:/root
            - ./files/library:/library
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        logging:
            driver: syslog
    postgres:
        image: postgres
        volumes:
            - ./files/postgresql/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=mari
            - POSTGRES_PASSWORD=example
            - POSTGRES_DB=marinesco
    pgadmin:
        image: dpage/pgadmin4
        links:
            - postgres
        ports:
            - 3334:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=root@srv.lan
            - PGADMIN_DEFAULT_PASSWORD=example
